### ISSUE TITLE
Search and Jump to Hierarchy Location

### ISSUE THREAD

**Issue by benjamin-heasly** [cims-bioko/cims-tablet#139]
Currently in modules like Census, the only way to get to a spot in the location hierarchy is to drill down from the top.

We would like to be able to search for an entity and jump directly to that entity's location in the hierarchy.  For example, we would like to be able to search for a location based on UNIQUEBID / extId, and then view that location in its correct hierarchy setting.

**Comment by batkinson** [comment]
This concept makes a fairly unrealistic assumption that an entity has one and only one associated parent value. In general this won't be true. For example consider a location that belongs to more than one district or an individual having two parents. The current application makes a number of these assumptions, but this limits the utility of the application for other contexts.

It would be far better to support interacting with entities outside of a hierarchy context and avoid having to construct a single valid path just to work on them.

**Comment by batkinson** [comment]
This is very closely related to #25
