### ISSUE TITLE
Add searching functionality for households

### ISSUE THREAD

**Issue by wolfe-lienhardt** [cims-bioko/cims-tablet#25]
Currently the only way to navigate households is by traversing the hierarchy.

Will implement a search fragment that will allow the user to enter things like household name, sector name, mapArea name etc. After entering the strings the necessary queries will be performed to create a new hierarchy path that will be auto filled and bring the user down to the desired location.

**Comment by batkinson** [comment]
Much of the functionality described above exists in the application after implementing #201, but this functionality as described above assumes a unique path to an entity. This will not generally be true. Depending on the reasons behind the request here, it may be better to consider alternative solutions.

Reducing the important of the hierarchy drill-down altogether may have many more advantages, such as geo-locating forms and using GIS-type queries to determine hierarchy information. This particular approach would eliminate *many* problems posed by the time dimension, such as admin redistricting and longitudinal analysis.
