### ISSUE TITLE
Model residencies in separate table

### ISSUE THREAD

**Issue by benjamin-heasly** [cims-bioko/cims-tablet#64]
Currently residencies are modeled as an Individual attribute.

To facilitate syncing data with the server, we will instead model residencies using a separate residency table.  The table will include columns for Individual Id and Location Id.

**Comment by batkinson** [comment]
Closing since it is no longer relevant to the recent versions of the application. Residency is no longer modeled as a separate entity. Also, syncing was changed considerably since this issue was made - it no longer presents major advantages anyway.
