### ISSUE TITLE
Crash when changing screen orientation between ODKCollect and OpenHDS

### ISSUE THREAD

**Issue by andrew-d-taylor** [cims-bioko/cims-tablet#97]
To reproduce the bug:
1. Launch any form from the application
2. Rotate the tablet and complete the form in this orientation

On attempting to return to the application after finalizing the form, the application crashes. The crash occurs before the data from the form can be persisted in the tablet's database. The form associated with the crash, however, remains in tact on the tablet.

**Comment by batkinson** [comment]
This has been fixed: see f7a50756c2
